@echo off
md src 2>nul
move app src\app 2>nul
md public\avatars 2>nul
md public\logos 2>nul
md public\icons 2>nul
md public\uploads 2>nul
md src\app\(auth)\login 2>nul
md src\app\(auth)\register 2>nul
md src\app\(auth)\forgot-password 2>nul
md src\app\(auth)\verify-email 2>nul
md src\app\dashboard\projects 2>nul
md src\app\dashboard\tasks 2>nul
md src\app\dashboard\team 2>nul
md src\app\dashboard\analytics 2>nul
md src\app\dashboard\settings 2>nul
md "src\app\workspace\[workspaceId]\files" 2>nul
md "src\app\workspace\[workspaceId]\board" 2>nul
md "src\app\workspace\[workspaceId]\whiteboard" 2>nul
md "src\app\workspace\[workspaceId]\chat" 2>nul
md "src\app\workspace\[workspaceId]\settings" 2>nul
md "src\app\chat\[conversationId]" 2>nul
md "src\app\meetings\[meetingId]" 2>nul
md "src\app\knowledge-base\[articleId]" 2>nul
md src\app\api\auth 2>nul
md "src\app\api\users\[userId]" 2>nul
md "src\app\api\projects\[projectId]" 2>nul
md "src\app\api\tasks\[taskId]" 2>nul
md "src\app\api\workspaces\[workspaceId]" 2>nul
md "src\app\api\chat\[conversationId]" 2>nul
md src\app\api\files 2>nul
md "src\app\api\meetings\[meetingId]" 2>nul
md src\app\api\analytics 2>nul
md src\app\api\gamification 2>nul
md src\app\api\notifications 2>nul
md src\app\api\search 2>nul
md src\components\ui 2>nul
md src\components\layout 2>nul
md src\components\dashboard 2>nul
md src\components\chat 2>nul
md src\components\workspace 2>nul
md src\components\analytics 2>nul
md src\lib 2>nul
md src\services 2>nul
md src\store 2>nul
md src\types 2>nul
md src\hooks 2>nul
md src\utils 2>nul
md src\styles 2>nul
md prisma 2>nul
echo Directories created.
